pipeline {
    agent any

     
    stages {
        stage('Compile and Clean') { 
            steps {

                bat 'mvn compile'
            }
        }
       
	stage('Junit5 Test') { 
           steps {

                bat 'mvn test'
            }
        }

      stage('Jacoco Report'){
        steps{
          jacoco() 
        }
      }

	stage('SonarQube'){
		steps{
				bat label: '', script: '''mvn sonar:sonar \
				-Dsonar.host.url=http://CDLVDIDEVMAN512:9000 \
				-Dsonar.login=88108fda4e57b044c4a2219c80b02b4e4b1d54f5'''
			}
   	}
      
     
      
        stage('Maven Build') { 
            steps {
                bat 'mvn clean install'
            }
        } 
        
        stage('Build Docker image'){
            steps {
              
               
            	 bat 'docker build -t  docker.repository.esi.adp.com/clientcentral/training:S2B3T4_expsys --build-arg VER=1.0 .'
			}
        }  
      stage('Docker Push'){
            steps {
                bat 'docker push docker.repository.esi.adp.com/clientcentral/training:S2B3T4_expsys'
            }
        }
        
        stage('Docker deploy'){
            steps {
               
                bat 'docker run -itd -p  8082:8082 docker.repository.esi.adp.com/clientcentral/training:S2B3T4_expsys'
             }
        }
     
    
    }
}
